### ISSUE TITLE
Kimai-mobile compatibility?

### ISSUE THREAD

**Issue by winfried** [gsantner/kimai-android#4]
Hi,

Would it be possible to make Kimai-android compatible with Kimai-mobile? ( http://www.kimai.org/kimai-mobile/ ) That would make a perfect match imho. It would even be better if there is a facility to switch between the two, so standard start-stop can be done from the mobile interface and more advanced tasks from the advanced interface.

Thanks a lot!

Winfried

**Comment by gsantner** [comment]
Hi @winfried ,
the last time I checked it out, it was quite outdated, but this seems to have changed now. I would still keep the normal kimai layout per default (because kimai-mobile needs to be installed explicitly). I would be open for a switch option, which would need updating settings, login workflow and navdrawer. 

The project is open for pull requests, shouln't be too hard to add this

**Comment by gsantner** [comment]
If you need more information ask.

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).

**Comment by gsantner** [comment]
I'm closing this as the app isn't updated for Kimai v2. And probably never will unless somebody is so friendly to start contributing. I myself don't use Kimai anymore, and as far I can see there haven't been any community interest/contribution in the past...so likely this won't ever happen.
